config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'mixes#index'

  resources :mixes

end

app/models/mix.rb
# == Schema Information
#
# Table name: mixes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  s3_path    :string(255)
#

class Mix < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mixes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  before_action :get_bucket
  before_action :get_mix, only: [:show, :destroy]

  # Right now, we're fetching objects direct from S3. We want to tie these objects with our own database,
  # So that we can include attached metadata.

  # Initial strategy: Create a 'Mix' object in postgres, storing the user-specified title as well as the sanitized
  # filename as the 's3_key'. Use that key to store in S3, and do the reverse when fetching.

  def index
    @mixes = Mix.all
  end

  def new

  end

  def show
    @mix_obj = AWS::S3::S3Object.find(@mix.s3_path, @bucket)
  end

  def create
    filename = sanitize_filename(params[:mix].original_filename)
    
    @mix = current_user.mixes.new(
      name:     params[:name],
      s3_path:  filename
    )
    

    begin 
      AWS::S3::S3Object.store(filename, params[:mix].read, @bucket, :access => :public_read) && @mix.save!
      redirect_to root_path
    rescue
      render :new, alert: "Upload failed"
    end


  end

  def destroy
    begin
      AWS::S3::S3Object.find(@mix.s3_path, @bucket).delete && @mix.destroy
      redirect_to root_path, notice: "File deleted!"
    rescue
      render :index, alert: 'Song could not be deleted'
    end
  end

  private

  def get_bucket
    @bucket = ENV["S3_BUCKET"]
  end

  def get_mix
    @mix = Mix.find(params[:id])
  end 

  def sanitize_filename(filename)
    returning filename.strip do |name|
     # NOTE: File.basename doesn't work right with Windows paths on Unix
     # get only the filename, not the whole path
     name.gsub!(/^.*(\\|\/)/, '')

     # Strip out the non-ascii character
     name.gsub!(/[^0-9A-Za-z.\-]/, '_')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blueberry Mix</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success" style="color: blue;"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" style="color: red"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/mixes/index.html.erb
<h2>Mixes index</h2>

<ul>
<% @mixes.each do |mix| %>
   <li><%= link_to mix.name, mix_path(mix) %> - <%= link_to "Delete",  mix_path(mix), method: :delete, confirm: 'Are you sure you want to delete ' + mix.name + '?' %></li>
<% end %>
</ul>

<strong><%= link_to "Add New Set", new_mix_path %></strong>

app/views/mixes/new.html.erb
<h2>Add New Mix</h2>

<%= form_tag mixes_path, :method => "post", :multipart => true do %>
    <%= text_field_tag "name" %><br>
    <%= file_field_tag "mix" %><br>
    <%= submit_tag "Upload" %>
<% end %>

app/views/mixes/show.html.erb
<h4>Listen to <%= @mix.name %></h4>

<%= content_tag :div, nil, class: 'set_player', data: { url: @mix_obj.url } %>